### PR TITLE
honor vertical display in setup();

### PR DESCRIPTION
**Pull request by t4nkw4rt**
if tile mode is TILE and screen height > screen width, then change mode to BSTACK.

### CODE REVIEW

**Comment by sulami** [comment]
Hm, I'm not sure I like this. I feel like just setting the default
tiling mode to bottom stack if you want it that way is a more intuitive
way of doing things.

-- 

Robin Schroer

**Comment by t4nkw4rt** [comment]
I think it's useful for persons with pivot monitors.  Then TILE mode adapts on the fly and no need to recompile. i3 does something similar. It also checks if height > width an then splits the containers default horizontal instead vertical.

**Comment by sulami** [comment]
Okay, I can see the point with pivot monitors. Should we then also
change bottom stack to tile in this case, effectively swapping the two?

-- 

Robin Schroer

**Comment by t4nkw4rt** [comment]
Makes sense to me.
Updating the code.
Future enhancement(?): check for root window geometry changes and adapt the tiling.

**Pull request merged**
